### PR TITLE
Fix dependabot for submodule updates

### PR DESCRIPTION
**Pull request by RAnders00**

### CODE REVIEW

**Comment by RAnders00** [comment]
Relevant error log from dependabot: https://github.com/pajbot/pajbot2/network/updates/83363369

**Comment by alazymeme** [comment]
Wouldn't it work similarly to fitignore? So instead using /folder/* should update everything? 🤔

**Comment by RAnders00** [comment]
The documentation doesnt say that wildcards are allowed, where did you read that? Either way, it currently doesn't work because it's expecting the directory to be the actual submodule, not the parent

**Comment by alazymeme** [comment]
> Either way, it currently doesn't work because it's expecting the directory to be the actual submodule, not the parent

This is why I was confused, I assumed it would just update everything in the folder...but it doesn't seem to be very well documented.

**Review by pajlada — APPROVED** [review]
👍

**Pull request merged**
