### PR TITLE
Package json file adjustments

### PR DESCRIPTION
**Pull request by alazymeme**
- Removing the `^` allows dependabot to update to major versions of dependencies: https://github.com/dependabot/feedback/issues/514#issuecomment-500368150
- Added bugs, homepage and license fields to package.json

### CODE REVIEW

**Comment by RAnders00** [comment]
I'm fairly sure dependabot already does major version upgrades, e.g. here: https://github.com/pajbot/pajbot2/pull/166

From how I understand it, the linked discussion says that major versions are only ignored when you configure `version_requirement_updates: off` in the dependabot yaml, and the version requirement has the `^`. Because we dont have `version_requirement_updates` disabled, we get major updates still.

**Comment by RAnders00** [comment]
Also, have you seen this? https://dependabot.com/docs/config-file/#version_requirement_updates It seems like we should just reconfigure dependabot instead of removing the `^`.

Problem is, removing the `^` means a `npm update` wont automatically update to new minor and patch versions anymore, which is generally desireable. https://docs.npmjs.com/about-semantic-versioning#using-semantic-versioning-to-specify-update-types-your-package-can-accept

**Comment by alazymeme** [comment]
> Also, have you seen this? https://dependabot.com/docs/config-file/#version_requirement_updates It seems like we should just reconfigure dependabot instead of removing the `^`.

Those are outdated docs, but I might be able to try the `versioning-strategy: increase` parameter in the new config: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates#versioning-strategy

**Comment by alazymeme** [comment]
I've reverted the relevant commits, will open a new pr for dependabot image

**Review by RAnders00 — APPROVED** [review]

**Pull request merged**
